// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeszetobwfionelkfwbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlc3pldG9id2Zpb25lbGtmd2JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjE3MjYsImV4cCI6MjA2ODY5NzcyNn0.ofWKxV6K6RjZpYqT-x0mmc13S3pdPqtx-3RQbfUONRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});